
FROM python:3.9-bookworm

WORKDIR /app
COPY app.py .
COPY requirements.txt .

RUN python3 -m pip install --upgrade pip
RUN pip install -r requirements.txt

EXPOSE 5000

ENTRYPOINT ["python"]
CMD ["app.py"]