services: 
  flask_sql_api: 
    image: flask_sql_api 
    stop_signal: SIGINT
    security_opt:
      - label:disable
    ports: 
      - '5000:5000'

  db:
    image: mysql
    security_opt:
      - label:disable
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_PASSWORD=An0thrS3crt
      - MYSQL_USER=onram
      - MYSQL_DATABASE=onram
    ports:
      - "3306:3306"
    volumes:
     - ./dbdata:/var/lib/mysql
     - ./init.sql:/docker-entrypoint-initdb.d/setup.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
